import subprocess

thresholds = [0.0, 0.01, 0.025, 0.04, 0.065, 0.08, 0.09, 0.14]
thresholds = [0.0, 0.12, 0.25, 0.5, 0.75, 1.0]
ping_freqs = [0.1, 0.2, 0.5, 1]

for ping_freq in ping_freqs:
    for threshold in thresholds:
        session_name = f"NN_threshold_{threshold}_fixed_0.9_sync_1_ping_{ping_freq}"
        command = f"sudo tsp docker run --rm --gpus all -v /home/redha/PRISMA_copy:/home/redha/PRISMA_copy -w /home/redha/PRISMA_copy/prisma allicheredha/prismacopy_episodes:offband python3 -u main.py --seed=100 --simTime=20 --train=1 --basePort=7000 --agent_type=dqn_buffer --session_name={session_name} --signaling_type=NN --logs_parent_folder=examples/5n_overlay_full_mesh_abilene/results/test_1 --traffic_matrix_root_path=examples/5n_overlay_full_mesh_abilene/traffic_matrices/ --traffic_matrix_index=0 --overlay_adjacency_matrix_path=examples/5n_overlay_full_mesh_abilene/topology_files/overlay_adjacency_matrix.txt --physical_adjacency_matrix_path=examples/5n_overlay_full_mesh_abilene/topology_files/physical_adjacency_matrix.txt --node_coordinates_path=examples/5n_overlay_full_mesh_abilene/topology_files/node_coordinates.txt --map_overlay_path=examples/5n_overlay_full_mesh_abilene/topology_files/map_overlay.txt --training_step=0.01 --batch_size=512 --lr=1e-05 --exploration_final_eps=0.01 --exploration_initial_eps=1.0 --iterationNum=5000 --gamma=1.0 --save_models=1 --start_tensorboard=0 --replay_buffer_max_size=10000 --link_delay=1 --load_factor=0.9 --sync_step=1 --max_out_buffer_size=16260 --sync_ratio=0.2 --signalingSim=1 --movingAverageObsSize=5 --prioritizedReplayBuffer=0 --activateUnderlayTraffic=1 --bigSignalingSize=35328 --groundTruthFrequence=1 --pingAsObs=1 --load_path=examples/5n_overlay_full_mesh_abilene/pre_trained_models/dqn_buffer --loss_penalty_type=fixed --snapshot_interval=20 --smart_exploration=0 --lambda_train_step=-1 --buffer_soft_limit=0 --lambda_lr=1.0000000000000002e-06 --lamda_training_start_time=0 --d_t_max_time=5 --pingPacketIntervalTime={ping_freq} --numEpisodes=20 --d_t_send_all_destinations=0 --rcpo_consider_loss=1 --reset_exploration=0 --rcpo_use_loss_pkts=1 --tunnels_max_delays_file_name=examples/5n_overlay_full_mesh_abilene/topology_files/max_observed_values.txt --gap_threshold={threshold}"
        train_id = int(subprocess.check_output(command, shell=True))
        print(f"train_id: {train_id}")

        for test_load in [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2]:
            command = f"sudo tsp -D {train_id} docker run --rm --gpus all -v /home/redha/PRISMA_copy:/home/redha/PRISMA_copy -w /home/redha/PRISMA_copy/prisma allicheredha/prismacopy_episodes:offband python3 -u main.py --seed=100 --simTime=25 --train=0 --basePort=7000 --agent_type=dqn_buffer --session_name={session_name} --signaling_type=ideal --logs_parent_folder=examples/5n_overlay_full_mesh_abilene/results/test_1 --traffic_matrix_root_path=examples/5n_overlay_full_mesh_abilene/traffic_matrices/ --traffic_matrix_index=0 --overlay_adjacency_matrix_path=examples/5n_overlay_full_mesh_abilene/topology_files/overlay_adjacency_matrix.txt --physical_adjacency_matrix_path=examples/5n_overlay_full_mesh_abilene/topology_files/physical_adjacency_matrix.txt --node_coordinates_path=examples/5n_overlay_full_mesh_abilene/topology_files/node_coordinates.txt --map_overlay_path=examples/5n_overlay_full_mesh_abilene/topology_files/map_overlay.txt --training_step=0.01 --batch_size=512 --lr=1e-05 --exploration_final_eps=0.01 --exploration_initial_eps=1.0 --iterationNum=5000 --gamma=1.0 --save_models=0 --start_tensorboard=0 --replay_buffer_max_size=10000 --link_delay=1 --load_factor={test_load} --sync_step=1 --max_out_buffer_size=16260 --sync_ratio=0.2 --signalingSim=1 --movingAverageObsSize=5 --prioritizedReplayBuffer=0 --activateUnderlayTraffic=1 --bigSignalingSize=35328 --groundTruthFrequence=1 --pingAsObs=1 --load_path=examples/5n_overlay_full_mesh_abilene/results/test_1/saved_models/{session_name}/final --loss_penalty_type=fixed --snapshot_interval=0 --smart_exploration=0 --lambda_train_step=-1 --buffer_soft_limit=0 --lambda_lr=1.0000000000000002e-06 --lamda_training_start_time=0 --d_t_max_time=5 --pingPacketIntervalTime={ping_freq} --numEpisodes=1 --d_t_send_all_destinations=0 --rcpo_consider_loss=1 --reset_exploration=0 --rcpo_use_loss_pkts=1 --tunnels_max_delays_file_name=examples/5n_overlay_full_mesh_abilene/topology_files/max_observed_values.txt --gap_threshold={threshold}"
            test_id = int(subprocess.check_output(command, shell=True))
            print(f"test_id: {test_id}")
