import os
import subprocess

root_folder = "5n_overlay_full_mesh_abilene"
# root_folder = "overlay_full_mesh_10n_geant"

command_root = "docker run --rm --gpus all -v /home/redha/prisma_chap4/prisma/:/app/prisma/ -w /app/prisma allicheredha/prisma:3.0"
target_update_period = 5
# run centralized MADRL and logit sharing with different ERs
for model_i, model in enumerate(["dqn_logit_sharing", "madrl_centralized"]):
    for er in [0.0, 0.25, 0.5, 0.75, 1.0]:
        for target_update_period in [5, 10]:
            for pingPacketIntervalTime in [0.01, 0.05, 0.1, 1, 5]:
                session_name = f"active_{model}_training_{target_update_period}_{er}_ping_{pingPacketIntervalTime}"
                command = f"python3 -u main.py --agent_type {model} --session_name {session_name} --nb_episodes 1 --train 1 --activateUnderlayTraffic 1 --map_overlay_path examples/{root_folder}/topology_files/map_overlay.txt --load_factor 0.4 --physical_adjacency_matrix_path examples/{root_folder}/topology_files/physical_adjacency_matrix.txt --overlay_adjacency_matrix_path examples/{root_folder}/topology_files/overlay_adjacency_matrix.txt --tunnels_max_delays_file_name examples/{root_folder}/topology_files/max_observed_values.txt --traffic_matrix_path examples/{root_folder}/traffic_matrices/node_intensity_normalized_0.txt --node_coordinates_path examples/{root_folder}/topology_files/node_coordinates.txt --logs_parent_folder examples/{root_folder}/continual_learning_results_new_final_ --saved_models_path examples/{root_folder}/continual_learning_results_new_final_/save_models/ --packet_size 516 --batch_size 512 --episode_duration 300 --pingAsObs 1 --logging_timestep 2 --pingPacketIntervalTime {pingPacketIntervalTime} --gap_threshold {er} --training_step 0.05 --target_update_period {target_update_period} --movingAverageObsSize 5 --iterationNum 1000 --exploration_initial_eps 1.0 --exploration_final_eps 0.01 --save_models 1 --lr 0.0001 --load_path examples/{root_folder}/pre_trained_models/dqn_buffer --replay_buffer_max_size 15000 --loss_penalty_type guided --controller_id {[-1, 0][model_i]} --lambda_train_step {target_update_period} --lambda_lr 0.1 --alpha 0.0 --perturbations 0 --auto_detect_loss 0 --monitoring_type active"

                print(f"{command_root} {command}")
                train_id = int(subprocess.check_output(f"tsp {command_root} {command}",shell=True,))

                ## launch evaluation with perturbations
                command = f"python3 -u main.py --agent_type {model} --session_name {session_name}_perturbed --nb_episodes 1 --train 1 --activateUnderlayTraffic 1 --map_overlay_path examples/{root_folder}/topology_files/map_overlay.txt --load_factor 0.4 --physical_adjacency_matrix_path examples/{root_folder}/topology_files/physical_adjacency_matrix.txt --overlay_adjacency_matrix_path examples/{root_folder}/topology_files/overlay_adjacency_matrix.txt --tunnels_max_delays_file_name examples/{root_folder}/topology_files/max_observed_values.txt --traffic_matrix_path examples/{root_folder}/traffic_matrices/node_intensity_normalized_0.txt --node_coordinates_path examples/{root_folder}/topology_files/node_coordinates.txt --logs_parent_folder examples/{root_folder}/continual_learning_results_new_final_ --packet_size 516 --batch_size 256 --episode_duration 300 --pingAsObs 1 --logging_timestep 2 --pingPacketIntervalTime {pingPacketIntervalTime} --gap_threshold {er} --saved_models_path examples/{root_folder}/continual_learning_results_new_final_/save_models/ --training_step 0.05 --target_update_period {target_update_period} --movingAverageObsSize 5 --iterationNum 1000 --exploration_initial_eps 0.0 --exploration_final_eps 0.0 --save_models 0 --lr 0.0001 --load_path  examples/{root_folder}/continual_learning_results_new_final_/save_models/{session_name}/final --replay_buffer_max_size 15000 --loss_penalty_type guided --controller_id {[-1, 0][model_i]} --lambda_train_step {target_update_period} --lambda_lr 0.1 --alpha 0.0 --perturbations 1 --auto_detect_loss 0 --monitoring_type active"
                test_id = int(subprocess.check_output(f"tsp -D {train_id} {command_root} {command}",shell=True,))
                print(test_id)

## run sp 
# command = f"docker run --rm --gpus all -v /home/redha/prisma_chap4/prisma/:/app/prisma/ -w /app/prisma allicheredha/prisma:3.0 python3 -u main.py --agent_type shortest_path --session_name ISP_default_path --nb_episodes 1 --train 0 --activateUnderlayTraffic 1 --map_overlay_path examples/{root_folder}/topology_files/map_overlay.txt --load_factor 0.4 --physical_adjacency_matrix_path examples/{root_folder}/topology_files/physical_adjacency_matrix.txt --overlay_adjacency_matrix_path examples/{root_folder}/topology_files/overlay_adjacency_matrix.txt --tunnels_max_delays_file_name examples/{root_folder}/topology_files/max_observed_values.txt --traffic_matrix_path examples/{root_folder}/traffic_matrices/node_intensity_normalized_0.txt --node_coordinates_path examples/{root_folder}/topology_files/node_coordinates.txt --logs_parent_folder examples/{root_folder}/continual_learning_results_new --saved_models_path examples/{root_folder}/continual_learning_results_new/save_models/ --packet_size 512 --batch_size 512 --episode_duration 300 --pingAsObs 1 --logging_timestep 2 --pingPacketIntervalTime 10000 --gap_threshold 0.0 --training_step 0.05 --target_update_period 5 --movingAverageObsSize 5 --iterationNum 1000 --exploration_initial_eps 0.0 --exploration_final_eps 0.0 --save_models 0 --loss_penalty_type guided --controller_id -1 --lambda_train_step 10 --lambda_lr 0.1 --alpha 0.0 --perturbations 1"

## opt
# command = "docker run --rm --gpus all -v /home/redha/prisma_chap4/prisma/:/app/prisma/ -w /app/prisma allicheredha/prisma:3.0 python3 -u main.py --agent_type oracle_routing --session_name Oracle_perturbed --nb_episodes 1 --train 0 --activateUnderlayTraffic 1 --map_overlay_path examples/{root_folder}/topology_files/map_overlay.txt --load_factor 0.4 --physical_adjacency_matrix_path examples/{root_folder}/topology_files/physical_adjacency_matrix.txt --overlay_adjacency_matrix_path examples/{root_folder}/topology_files/overlay_adjacency_matrix.txt --tunnels_max_delays_file_name examples/{root_folder}/topology_files/max_observed_values.txt --traffic_matrix_path examples/{root_folder}/traffic_matrices/node_intensity_normalized_0.txt --node_coordinates_path examples/{root_folder}/topology_files/node_coordinates.txt --logs_parent_folder examples/{root_folder}/continual_learning_results_new/final --saved_models_path examples/{root_folder}/continual_learning_results_new/save_models/ --packet_size 512 --batch_size 512 --episode_duration 300 --pingAsObs 1 --logging_timestep 2 --pingPacketIntervalTime 10000 --gap_threshold 0.0 --training_step 0.05 --target_update_period 5 --movingAverageObsSize 5 --iterationNum 1000 --exploration_initial_eps 0.0 --exploration_final_eps 0.0 --save_models 0 --loss_penalty_type guided --controller_id -1 --lambda_train_step 10 --lambda_lr 0.1 --alpha 0.0 --perturbations 1 --optimal_solution_path examples/{root_folder}/optimal_solution/real/30_ut_minCostMCF.json"